### ISSUE TITLE
Exception swallowed on incorrect script definitions

### ISSUE THREAD

**Issue by jeeger** [python-poetry/poetry-plugin-bundle#134]
With the following configuration, `poetry bundle venv /tmp/venv` does not error, but does not produce a correct bundle (the code of the project itself is not bundled). The cause is the dash in the script definition. `poetry install` does not cause an error in this case. 
The exception is printed when `-vvv` is passed, but it seems to be ignored when `-vvv` is not used.

```toml
[project]
name = "test"
version = "0.1.0"
description = ""
authors = [
    {name = "Your Name",email = "you@example.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
test-script = "test.test-script:main"
```
